## Classification Using different Classification Algorithms

### Load Data

In [1]:
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit

# load data
df = pd.read_csv('dataset/data_bc_scaled.csv')

# Split features and Labels
X = df.iloc[:, :-1]#.to_numpy()
y = df.iloc[:, -1]#.to_numpy()

# Stratified split in train set and test set
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.1, random_state=42)
for train_index, test_index in sss.split(X,y):
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y.loc[train_index], y.loc[test_index]

In [2]:
def print_result(y_pred, y):
    print("Accuracy Score: ", accuracy_score(y_pred, y_test))
    print("Precision Score: ", precision_score(y_pred, y_test))
    print("Recall Score: ", recall_score(y_pred, y_test))
    print("Confusion Matrix: \n", confusion_matrix(y_pred, y_test))

### SGD Classifier

In [17]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.model_selection import cross_val_predict

# train classifier
sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train,y_train)
y_pred = sgd_clf.predict(X_test)
print_result(y_pred, y_test)


Accuracy Score:  0.9649122807017544
Precision Score:  0.9523809523809523
Recall Score:  0.9523809523809523
Confusion Matrix: 
 [[35  1]
 [ 1 20]]


### Random Forest Classifier

In [18]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(n_estimators=100)
rf_clf.fit(X_train,y_train)
y_pred = rf_clf.predict(X_test)
print_result(y_pred, y_test)

Accuracy Score:  1.0
Precision Score:  1.0
Recall Score:  1.0
Confusion Matrix: 
 [[36  0]
 [ 0 21]]


### Support Vector Machine

In [19]:
from sklearn.svm import SVC

svm_clf = SVC()
svm_clf.fit(X_train,y_train)
y_pred = svm_clf.predict(X_test)
print_result(y_pred, y_test)

Accuracy Score:  0.9824561403508771
Precision Score:  0.9523809523809523
Recall Score:  1.0
Confusion Matrix: 
 [[36  1]
 [ 0 20]]


### Naive Bayes Classification

In [50]:
from sklearn.naive_bayes import GaussianNB

gnb_clf = GaussianNB()
gnb_clf.fit(X_train,y_train)
y_pred = gnb_clf.predict(X_test)
print_result(y_pred, y_test)

Accuracy Score:  0.9298245614035088
Precision Score:  0.9047619047619048
Recall Score:  0.9047619047619048
Confusion Matrix: 
 [[34  2]
 [ 2 19]]
